# Generated by Django 6.0 on 2025-12-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicalcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
